name: tvkabel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.1.1
  flutter_svg: ^1.1.6
  get: 4.6.5
  wave: ^0.2.2
  firebase_auth: ^4.1.0
  cloud_firestore: 4.0.4
  select_form_field: 2.2.0
  intl: 0.17.0
  # month_year_picker: 0.2.0+3
  pdf: 3.8.4
  printing: 5.9.3
  path_provider: 2.0.11
  #open_file: 3.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

